# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
    - script: echo Build step
      displayName: 'Run build'

- job: Test
  dependsOn: Build  # Ce job dépend de "Build", donc s'exécutera après.
  steps:
    - script: echo Test step
      displayName: 'Run tests'
