name:  Pytest & flake8 control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r dev_requirements.txt
          pip install -r src/requirements.txt

      - name: Run flake8
        uses: py-actions/flake8@v2

      - name: Run tests
        run: |
          pytest -v --cov=src


