name: Sync to Azure DevOps

on:
  push:
    branches:
      - main
      - dev_thomas
      - dev_nath
      - dev_lo
      - dev-ben

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "thomas.awounfouet@gmail.com"
          git config --global user.name "ton-nom"

      - name: Push changes to Azure DevOps
        run: |
          git remote add azure https://dev.azure.com/datascientest-project/_git/crypto-bot-v2
          git push azure main
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}  # Assure-toi que ce secret est bien défini